### ISSUE TITLE
[FEAT] 장바구니 개수 조회 API 구현

### ISSUE THREAD

**Issue by ckkim817** [SOPT-all/35-COLLABORATION-SERVER-AMAZON#14]
## 💡 Issue

- 클라 측 요청으로 장바구니 개수를 조회하는 API를 구현합니다.

## 📝 To-do

- [ ] DTO, Mapper 정의
- [ ] Controller 엔드포인트 작성
- [ ] Service 비즈니스 로직 구현
- [ ] 성공 응답 및 예외 처리
- [ ] Postman 테스트
