### ISSUE TITLE
[FEAT] 유저 검색 기록 조회 API 구현

### ISSUE THREAD

**Issue by ckkim817** [SOPT-all/35-COLLABORATION-SERVER-AMAZON#5]
## 💡 Issue

- 유저가 본인의 검색 기록을 조회하는 API를 구현합니다.

## 📝 To-do

- [ ] 도메인 모델(Entity) 정의
- [ ] DTO(Record) 정의
- [ ] Repository 인터페이스 생성
- [ ] Service 클래스 작성
- [ ] Controller 클래스 작성
- [ ] 성공 응답 및 예외 처리
- [ ] Postman 테스트
