### ISSUE TITLE
[FEAT] 상품 검색 조회 API 구현 

### ISSUE THREAD

**Issue by gahyuun** [SOPT-all/35-COLLABORATION-SERVER-AMAZON#6]
## 💡 Issue

-  검색한 상품들을 노출시키는 API

## 📝 To-do

- [ ] 도메인 모델(Entity) 정의
- [ ] DTO(Record) 정의
- [ ] Repository 인터페이스 생성
- [ ] Service 클래스 작성
- [ ] Controller 클래스 작성
- [ ] 성공 응답 및 예외 처리
